Project_2/djangoProject/cars/urls.py
from django.urls import path
from . import views

app_name = 'cars'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/more/', views.more_details, name='more'),
    path('cart/', views.Cart.as_view(), name='cart'),
    path('checkout/', views.Checkout.as_view(), name='checkout'),
]

Project_2/djangoProject/cars/templates/cars/cart.html
{% extends "cars/header.html" %}
{% load static %}
{% block title %}Car Order{% endblock %}
{% block page_title %}<a href="{% url 'cars:index' %}" style="color: black; text-decoration: none;">Car Order</a>{% endblock %}
{% block content %}
    <div class="container d-grid col-9">
        <div class="page_list d-grid">
            {% include 'cars/includes/messages.html' %}
            {% if cart_list %}
                <table id="customers">
                    <tr>
                        <th style="font-weight:bold">Image:</th>
                        <th style="font-weight:bold">VIN:</th>
                        <th style="font-weight:bold">Title:</th>
                        <th style="font-weight:bold">Quantity:</th>
                        <th style="font-weight:bold">Price:</th>
                        <th style="font-weight:bold"></th>
                    </tr>
                    {% for car in cart_list %}
                        <tr>
                            <th style="font-weight:bold">
                                {% if car.image_url %}
                                    <div class="text-center"><img src="{{ car.image_url }}" alt="No car available." class="car_image" style="border-radius: 10px; padding-bottom: 0px;"></div>
                                {% else %}
                                    <div class="text-center"><img src="{% static 'cars/images/no_car.svg' %}" alt="No car available." class="car_image" style="border-radius: 10px; padding-bottom: 0px;"></div>
                                {% endif %}
                            </th>
                            <th>{{ car.vin }}</th>
                            <th>{{ car.title }}</th>
                            <th>{{ car.stock_number }}</th>
                            <th>{{ car.sale_price }}</th>
                            <th>
                                <form action="{% url 'cars:cart' %}" method="get">
                                    <button name="remove" value="{{ car.id }}" type="submit" class="btn btn-dark container" style="font-size: 17px">Remove</button>
                                </form>
                            </th>
                        </tr>
                    {% endfor %}
                </table>
            {% else %}
                <p class="text-center" style="font-size: 200%">Add products to your cart.</p>
            {% endif %}
        </div>
        <div class="btn-group">
            <div class="container">
                <a href="{% url 'cars:index' %}" type="submit" class="btn btn-dark container" style="font-size: 17px; border-radius: 10px">Add more</a>
            </div>
            <div class="container">
                <form action="{% url 'cars:checkout' %}" method="get">
                    <button type="submit" class="btn btn-primary container" style="font-size: 17px; border-radius: 10px">Checkout</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

Project_2/djangoProject/cars/templates/cars/checkout.html
{% extends "cars/header.html" %}
{% block title %}Car Checkout{% endblock %}
{% block page_title %}<a href="{% url 'cars:cart' %}" style="color: black; text-decoration: none;">Car Checkout</a>{% endblock %}
{% block card_content %}
    {% load crispy_forms_tags %}
    {{ form|crispy }}
{% endblock %}
{% block card_button %}Buy{% endblock %}
{% block card_footer %}
    <p class="text-center">If you've changed your mind, go back to your <a href="{% url 'cars:cart' %}">cart</a>.</p>
{% endblock %}

Project_2/djangoProject/cars/templates/cars/detail.html
{% extends "cars/header.html" %}
{% load static %}
{% block title %}Car Details | {{ car.vin }}{% endblock %}
{% block page_title %}<a href="{% url 'cars:index' %}" style="color: black; text-decoration: none;">Car Details</a>{% endblock %}
{% block content %}
    <form action="{% url 'cars:more' car.id %}" method="get">
        <div class="container d-grid col-9">
            <div class="page_list d-grid">
                {% if car.image_url %}
                    <div class="text-center"><img src="{{ car.image_url }}" alt="No car available." class="car_image"></div>
                {% else %}
                    <div class="text-center"><img src="{% static 'cars/images/no_car.svg' %}" alt="No car available." class="car_image"></div>
                {% endif %}
                <label class="text-center" style="padding: 20px; font-size: 25px"><strong>{{ car.short_title }}</strong></label>
                {% include 'cars/includes/messages.html' %}
                <table id="customers">
                        <tr>
                            <th style="font-weight:bold">Detail</th>
                            <th style="font-weight:bold">Value</th>
                        </tr>
                        <tr>
                            <th>VIN: </th>
                            <th>{{ car.vin }}</th>
                        </tr>
                        <tr>
                            <th>Maker: </th>
                            <th>{{ car.make }}</th>
                        </tr>
                        <tr>
                            <th>Model: </th>
                            <th>{{ car.model }}</th>
                        </tr>
                    {% for name_detail, detail in car_detail.items %}
                        {% if detail %}
                            <tr>
                                <th>{{ name_detail }}</th>
                                <th>{{ detail }}</th>
                            </tr>
                        {% endif %}
                    {% endfor %}
                </table>
            </div>
            <div class="text-center" style="padding: 7px">
                <input type="submit" value="Fetch more details" class="container d-grid">
            </div>
        </div>
    </form>
{% endblock %}

Project_2/djangoProject/cars/templates/cars/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/svg" href="{% static 'cars/images/car_logo.svg' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'cars/style.css' %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
{% block user %}
    <div class="page_title text-center page_form">
        <div class="welcome">Welcome, <a href="{% url 'profile' %}">{{ user.get_short_name }}</a></div>
        <h1>{% block page_title %}{% endblock %}</h1>
        <form action="{% url 'logout' %}" method="get">
            <button class="btn btn-primary logout" type="submit">
                Logout
            </button>
        </form>
    </div>
{% endblock %}
{% block content %}
    <div class="container mb-3">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                <div class="card shadow-lg border-0 rounded-lg mt-5 mb-5">
                    {% block card_title %}{% endblock %}
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            {% block card_content %}{% endblock %}
                            <br>
                            <button type="submit" class="btn btn-dark container" style="font-size: 25px">{% block card_button %}{% endblock %}</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        {% block card_footer %}{% endblock %}
    </div>
{% endblock %}
</body>
</html>

Project_2/djangoProject/cars/templates/cars/index.html
{% extends "cars/header.html" %}
{% block title %}Car List{% endblock %}
{% block page_title %}<a href="{% url 'cars:index' %}" style="color: black; text-decoration: none;">Car List</a>{% endblock %}
{% block content %}
<div class="container d-grid col-9">
    {% include 'cars/includes/messages.html' %}
    <form action="{% url 'cars:index' %}" method="get">
        <div class="text-center" style="padding: 7px">
            <input name="vin" type="text" placeholder="Search VIN...">
        </div>
    </form>
    <div class="page_list d-grid">
        {% if car_list %}
            <table id="customers">
                <tr>
                    <th style="font-weight:bold">Vehicle Identification number (VIN)</th>
                    <th style="font-weight:bold">Make</th>
                    <th style="font-weight:bold">Model</th>
                    <th style="font-weight:bold">Order</th>
                </tr>
            {% for car in car_list %}
                <tr>
                    <th><a href="{% url 'cars:detail' car.id %}">{{ car.vin }}</a></th>
                    <th>{{ car.make }}</th>
                    <th>{{ car.model }}</th>
                    <th>
                        <form action="{% url 'cars:cart' %}" method="post">
                            {% csrf_token %}
                            <button name="car_id" value="{{ car.id }}" type="submit" class="btn btn-dark container" style="font-size: 17px">Add to cart</button>
                        </form>
                    </th>
                </tr>
            {% endfor %}
            </table>
        {% else %}
            <p class="text-center" style="font-size: 200%">No cars are available.</p>
        {% endif %}
    </div>
    <div class="pagination list_pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}
            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
</div>
{% endblock %}